In [1]:
import cv2
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data_dir = "../src/datasets/cholec/train/groundtruth/"
files = os.listdir(data_dir)

In [3]:
u = np.array([999, 999, 999])
v = []
w = []

for i in range(len(files)):
    file_name = os.path.join(data_dir, files[i])
    img = cv2.imread(file_name)
    #img = cv2.COLOR_BGR2RGB(img)
    unique = np.unique(img.reshape((-1,3)), axis=0)
    
    for val in unique:
        if val not in u:
            print(val)
            u = np.vstack((u, val))

[  0 255 170]
[ 75 183 186]
[114 114 255]
[127 127 127]
[140 140 210]
[156  70 231]
[128  50   0]
[217 160 160]


In [ ]:
print(u)
print("\nunique colors:", len(u))

In [8]:
print(v)
print("\nunique colors:", len(v))


unique colors: 6165


In [ ]:
print(w)
print("\nunique colors:", len(w))

In [ ]:
train = [0, 70, 75, 114, 127, 140, 156, 160, 165, 170, 183, 186, 210, 231, 255, 85, 169, 184, 74, 111, 50, 128, 217]
val = [75, 114, 127, 140, 160, 165, 183, 186, 210, 255, 0, 169, 170, 184, 70, 156, 231, 74, 111, 85, 50, 128]
test = [0, 75, 114, 127, 140, 160, 165, 170, 183, 186, 210, 255, 70, 156, 231, 50, 85, 128, 169, 184, 74, 111, 88, 130, 193]

In [ ]:
total = train + val + test

In [ ]:
total = np.array(total)
total_unique = np.unique(total)

In [ ]:
print(total_unique)

In [ ]:
print(len(total_unique))

In [ ]:
data_dir = "../src/datasets/cholec/train/groundtruth/"
files = os.listdir(data_dir)

In [ ]:
u = []

for i in tqdm(range(len(files))):
    file_name = os.path.join(data_dir, files[i])
    img = cv2.imread(file_name)
    unique = np.unique(img, axis=[0,1])
    
    for val in unique:
        if val not in u:
            u.append(val)

# Test Interactive Plots

In [4]:
import mpld3
from mpld3 import plugins
from mpld3.utils import get_id
import numpy as np
import collections
import matplotlib.pyplot as plt

N_paths = 5
N_steps = 100

x = np.linspace(0, 10, 100)
y = 0.1 * (np.random.random((N_paths, N_steps)) - 0.5)
y = y.cumsum(1)

fig, ax = plt.subplots()
labels = ["a", "b", "c", "d", "e"]
line_collections = ax.plot(x, y.T, lw=4, alpha=0.2)
interactive_legend = plugins.InteractiveLegendPlugin(line_collections, labels)
plugins.connect(fig, interactive_legend)

mpld3.display()